name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Ensure it triggers on the 'master' branch, not 'main'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (optional, if your project requires Node.js)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify Node.js version (adjust if needed)

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project (e.g., build static files if applicable)
      - name: Build the project
        run: npm run build  # Make sure 'npm run build' works locally first

      # Step 5: Deploy the build files to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          folder: ./build  # Ensure the 'build' folder contains your built files
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this token
