name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the main branch
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (if your project uses it)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version (you can adjust this version as needed)

      # Step 3: Install dependencies (if you use npm/yarn)
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project (if applicable, like in React, Vue, etc.)
      - name: Build the project
        run: npm run build  # Adjust this to match your build command (e.g., npm run build)

      # Step 5: Deploy to GitHub Pages (using the peaceiris action)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # This is the directory where the generated content (HTML, CSS, JS) is located
          folder: ./build  # Change to your build folder if different, e.g., ./dist for some frameworks
        env:
          # Provide your GitHub token for authentication (GitHub automatically provides this)
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
